services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ~/.ssh:/root/.ssh:ro
    depends_on:
      - mysql
      - redis
    environment:
      - TZ=America/Sao_Paulo

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: intranet_dev_root
      MYSQL_DATABASE: intranet
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin_dev
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set local http://minio:9000 minioadmin minioadmin_dev) do echo 'aguardando minio...' && sleep 2; done;
      mc mb -p local/repositorio;
      exit 0;
      "

  onlyoffice:
    image: onlyoffice/documentserver
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=troque_essa_chave_super_secreta_onlyoffice
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
    ports:
      - "8082:80"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mysql_data:
  minio_data:
  onlyoffice_data:
